import Head from 'next/head'
import { client } from '../lib/apollo'
import { gql } from '@apollo/client'
import NextLink from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({ posts }) {
  const DateFormat = a => {
    return new Date(a).toLocaleDateString()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>WordPress learning</h1>
      {/* <ul>
        {pages.map(i => {
          return (
            <NextLink key={i.node.id} href={`${i.node}`}>
              <a style={{ color: 'blue' }}> {`${i.node.menuItems.label}`} </a>
            </NextLink>
          )
        })}
      </ul> */}
      <main className={styles.main}>
        {/* <pre>{JSON.stringify(pages, null, 2)}</pre> */}
        {/* <div dangerouslySetInnerHTML={{ __html: content }} /> */}
        <ul>
          {posts.map(i => {
            return (
              <li key={i.date}>
                <NextLink href={`/post/${i.slug}`}>
                  <a style={{ color: 'blue' }}>
                    {DateFormat(i.date)} - {i.title}
                  </a>
                </NextLink>
              </li>
            )
          })}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const result = await client.query({
    query: gql`
      query GetPostsWordPressAndURL {
        # pageBy(uri: "/about") {
        #   title
        #   content
        # }

        posts {
          nodes {
            date
            title
            slug
          }
        }
      }
    `
  })

  return {
    props: {
      posts: result.data.posts.nodes
      // title: result.data.pageBy.title,
      // content: result.data.pageBy.content,
      // pages: result.data.menus.edges
    }
  }
}
